### ISSUE TITLE
core dump because of closure function in redhat linux

### ISSUE THREAD

**Issue by haifenghuang** [small-c/wobj#1]
As the title says, when I compile the foo.c with `gcc foo.c`, there is no problem. But when I run the program, I got below output:

```
Clofn: could't change memory type of C.malloc allocated!
Clofn: could't change memory type of C.malloc allocated!
Segmentation fault (core dumped)
```

My OS:

```
$ uname -a
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I check the error message from the source, the problem comes from `__wobj_ativ_mem` function.

**Comment by wy3** [comment]
You can see:

https://github.com/small-c/wobj/blob/59a72ea62dc2f6907b9b459bcd2d097e17f7fac6/wobj.h#L98-L103
> In this case, the memory is allocated from **malloc** was **NULL** or cannot access. And then, the function returns **NULL**.

then,

https://github.com/small-c/wobj/blob/59a72ea62dc2f6907b9b459bcd2d097e17f7fac6/tests/foo.c#L50-L53

> **foo** got **NULL** and cannot access to its property/method, segmentation fault!

- On Linux, the library is tested on Ubuntu 16.04 and Windows 10 WLS, but Redhat had no.
- I think the program ran on low memory.

> Sorry for my late reply.

**Comment by haifenghuang** [comment]
I got it solved after I issue below commands:

```sh
[hhf@localhost tests]$ getenforce
Enforcing

[hhf@localhost tests]$ sudo setenforce 0
[sudo] password for hhf: 
[hhf@localhost tests]
```
